CREATE OR REPLACE FUNCTION TSIZE RETURN NUMBER
AS
TS NUMBER;
BEGIN
  SELECT AVG(COUNT(*))
  INTO TS
  FROM LINEITEM
  GROUP BY L_ORDERKEY;

  RETURN(TS);
END;
/

show errors

SELECT COUNT(*)
FROM ( SELECT L_ORDERKEY, COUNT(*)
       FROM LINEITEM
       GROUP BY L_ORDERKEY
       HAVING COUNT(*) > (SELECT DISTINCT TSIZE
                          FROM LINEITEM) );

